### ISSUE TITLE
Update Decorators to Stage 3?

### ISSUE THREAD

**Issue by NullVoxPopuli** [test262-fyi/test262.fyi#83] opened 2024-12-01 01:18 UTC
https://github.com/tc39/proposal-decorators

![image](https://github.com/user-attachments/assets/b7e89f69-cc0c-42ec-9894-85ab0ca4b0fb)

But on the site:
![image](https://github.com/user-attachments/assets/fe06a3d9-4576-483b-bd26-7475306f0f2e)

**Comment by linusg** [comment] 2024-12-01 01:32
Duplicate of https://github.com/test262-fyi/test262.fyi/issues/43, someone needs to update https://tc39.es/proposal-decorators/

**Closed by linusg** 2024-12-01 01:32 UTC

**Comment by NullVoxPopuli** [comment] 2024-12-01 01:39
thank you!
